name: Backoffice Deploy

on: [workflow_dispatch]
 
permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: api-eu-backoffice  
  AZURE_WEBAPP_PACKAGE_PATH: './src/Booka.Backoffice/publish'
  DOTNET_VERSION: '8.0.x'
  WORKING_DIRECTORY: './src/Booka/Booka.Backoffice'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore project
        run: dotnet restore ${{ env.WORKING_DIRECTORY }} 

      - name: Build project
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout