name: WebApp Deploy

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: 8.0.x
  PROJECT_PATH: src/Booka/Booka.WebApp/Booka.WebApp.csproj
  AZURE_WEBAPP_PACKAGE_PATH: ./Booka.WebApp/publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Prepare and build project
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-restore --no-build -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      # Deploy to Azure
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_APP_NAME }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      # Logout from azure
      - name: Logout from Azure
        run: az logout
